package:
    name: fiona
    version: "1.6.3"

source:
    git_rev: 1.6.3
    git_url: https://github.com/Toblerity/Fiona.git

requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - cython
    - gdal ==1.11.3
    - bzip2 >=1.0.6
    - zlib >=1.2.7
    - six

  run:
    - python
    - gdal ==1.11.3
    - bzip2 >=1.0.6
    - zlib >=1.2.7
    - six

build:
    number: 0

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD
  summary: "gis vector feature data"
