package:
  name: graph-tool
  version: "2.2.38"

source:
  git_url: https://git.skewed.de/count0/graph-tool.git

requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - numpy
    - scipy
    - matplotlib
    - bzip2
    - zlib
    - expat >=2.1.0.1
    - graphviz
    - cairo
    - cairomm
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - fontconfig
    - sparsehash >=2.0.2
    - boost >=1.56.0 # [py3k]
    - boost >=1.56.0 # [py2k]
    - cgal
    - mpfr
    - gmp
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - bzip2
    - zlib
    - expat >=2.1.0.1
    - graphviz
    - cairo
    - cairomm
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - fontconfig
    - sparsehash >=2.0.2
    - boost >=1.56.0 # [py3k]
    - boost >=1.56.0 # [py2k]
    - cgal
    - mpfr
    - gmp

build:
  number: 1

about:
  home: http://graph-tool.skewed.de/
  license: GPLv3
  summary: "Graph-tool is an efficient Python module for manipulation and statistical analysis of graphs (a.k.a. networks)."
