package:
  name: pygobject
  version: "3.10.2"

source:
  fn: pygobject-3.10.2.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.10/pygobject-3.10.2.tar.xz


requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - zlib
    - libffi
    - gettext
    - cairo
    - py2cairo # [py2k]
    - pycairo # [py3k]

  run:
    - python
    - zlib
    - libffi
    - gettext
    - cairo
    - py2cairo # [py2k]
    - pycairo # [py3k]

build:
  number: 1

about:
  home: https://wiki.gnome.org/action/show/Projects/PyGObject?action=show&redirect=PyGObject
  license: GPLv3
  summary: "pygobject"
