package:
  name: cairo
  version: 1.14.2

source:
  fn: cairo-1.14.2.tar.xz
  url: http://cairographics.org/releases/cairo-1.14.2.tar.xz

build:
  number: 1

requirements:
  build:
    - freetype
    - fontconfig
    - libpng
    - pixman
    - zlib
  run:
    - freetype
    - fontconfig
    - libpng
    - pixman
    - zlib

about:
  home: http://cairographics.org/
  license: LGPL 2.1 and MPL 1.1
  summary: "Cairo is a 2D graphics library with support for multiple output devices"
