package:
  name: cairo
  version: 1.12.18

source:
  fn: cairo-1.12.18.tar.xz
  url: http://cairographics.org/releases/cairo-1.12.18.tar.xz
  md5: 8e4ff32b82c3b39387eb6f5c59ef848e

build:
  number: 1

requirements:
  build:
    - freetype
    - fontconfig
    - libpng
    - pixman
    - zlib
  run:
    - freetype
    - fontconfig
    - libpng
    - pixman
    - zlib

about:
  home: http://cairographics.org/
  license: LGPL 2.1 and MPL 1.1
  summary: "Cairo is a 2D graphics library with support for multiple output devices"
