package:
  name: graph-tool
  version: "2.2.43"

source:
  git_url: https://git.skewed.de/count0/graph-tool.git
  git_tag: release-2.2.43

requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - numpy
    - scipy
    - matplotlib
    - bzip2
    - zlib
    - expat >=2.1.0.1
    - graphviz
    - cairo
    - cairomm
    - fontconfig
    - sparsehash >=2.0.2
    - boost
    - cgal ==4.5.2
    - mpfr
    - gmp
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - libpng15

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - bzip2
    - zlib
    - expat >=2.1.0.1
    - graphviz
    - cairo
    - cairomm
    - fontconfig
    - sparsehash >=2.0.2
    - boost
    - cgal ==4.5.2
    - mpfr
    - gmp
    - py2cairo # [py2k]
    - pycairo # [py3k]
    - libpng15

build:
  number: 1
  binary_relocation: true

about:
  home: http://graph-tool.skewed.de/
  license: GPLv3
  summary: "Graph-tool is an efficient Python module for manipulation and statistical analysis of graphs (a.k.a. networks)."
