package:
  name: expat
  version: 2.1.0.2

source:
  fn: expat-2.1.0.tar.gz # [unix]
  url: http://downloads.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz # [unix]

requirements:
  build:
    - zlib

  run:
    - zlib

build:
  number: 1

about:
  home: http://www.libexpat.org/
  license: GPL
  summary: "Expat is an XML parser library written in C"
