package:
  name: geopandas
  version: 0.1.0

source:
  git_url: https://github.com/geopandas/geopandas.git

build:
  number: 0

requirements:
  build:
    - python
    - bzip2
    - zlib
    - numpy
    - pandas
    - fiona
    - six
    - pyproj
  run:
    - python
    - bzip2
    - zlib
    - numpy
    - pandas
    - fiona
    - six
    - pyproj

about:
  home: http://geopandas.org/install.html
  license: LGPL 2.1 and MPL 1.1
  summary: "GeoPandas is an open source project to make working with geospatial data in python easier. GeoPandas extends the datatypes used by pandas to allow spatial operations on geometric types. Geometric operations are performed by shapely. Geopandas further depends on fiona for file access and descartes and matplotlib for plotting."
