package:
  name: fontconfig
  version: 2.11.1

source:
  fn: fontconfig-2.11.1.tar.bz2 # [unix]
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.1.tar.bz2 # [unix]

build:
  number: 4

requirements:
  build:
    - zlib
    - freetype
    - expat
    - libpng
    - bzip2
  run:
    - zlib
    - freetype
    - expat
    - libpng
    - bzip2

about:
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: GPL
  summary: "Fontconfig is a library for configuring and customizing font access."
