package:
    name: boost
    version: "1.58.0"

source:
    fn: boost_1_58_0.tar.bz2 # [unix]
    url: http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.58.0%2Fboost_1_58_0.tar.bz2%2Fdownload&ts=1461674341&use_mirror=nbtelecom
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - bzip2 >=1.0.6
    - zlib
  run:
    - python
    - bzip2 >=1.0.6

build:
  number: 2

about:
  home: http://www.boost.org/
  license: Boost Software License
  summary: "Boost provides free peer-reviewed portable C++ source libraries."
