package:
    name: boost
    version: "1.58.0"

source:
    fn: boost_1_58_0.tar.bz2 # [unix]
    url: https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2 # [unix]
    sha256: "fdfc204fc33ec79c99b9a74944c3e54bd78be4f7f15e260c0e2700a36dc7d3e5"
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - bzip2 >=1.0.6
    - zlib >=1.2.7
  run:
    - python
    - bzip2 >=1.0.6
    - zlib >=1.2.7

build:
  number: 4

about:
  home: http://www.boost.org/
  license: Boost Software License
  summary: "Boost provides free peer-reviewed portable C++ source libraries."
