package:
    name: boost
    version: "1.60.0"

source:
    fn: boost_1_60_0.tar.gz # [unix]
    url: http://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.60.0%2F&ts=1451655402&use_mirror=netcologne # [unix]
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - bzip2 >=1.0.6
    - zlib >=1.2.7
  run:
    - python
    - bzip2 >=1.0.6
    - zlib >=1.2.7

build:
  number: 0

about:
  home: http://www.boost.org/
  license: Boost Software License
  summary: "Boost provides free peer-reviewed portable C++ source libraries."
