package:
    name: cgal
    version: "4.7"

source:
    fn: CGAL-4.7.tar.gz
    url: https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.7/CGAL-4.7.tar.gz

requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - boost ==1.58
    - gmp
    - mpfr
    - zlib
  run:
    - boost ==1.58
    - gmp
    - mpfr

build:
  number: 4

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: "Computational Geometry Algorithms Library"
