package:
  name: ttfquery
  version: !!str 1.0.5

source:
  fn: TTFQuery-1.0.5.tar.gz
  url: https://pypi.python.org/packages/source/T/TTFQuery/TTFQuery-1.0.5.tar.gz
  md5: 6e01d38684eb94978fad70eba4c68463

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - ttfquery

about:
  home: http://ttfquery.sourceforge.net/
  license: BSD License
  summary: 'FontTools-based package for querying system fonts'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
