package:
    name: shapely
    version: "1.5.13"

source:
    git_rev: 1.5.13
    git_url: https://github.com/Toblerity/Shapely.git

requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - geos ==3.5.0
    - bzip2 >=1.0.6
    - zlib >=1.2.7

  run:
    - python
    - geos ==3.5.0
    - bzip2 >=1.0.6
    - zlib >=1.2.7

build:
    number: 5

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD
  summary: "Python package for manipulation and analysis of geometric objects in the Cartesian plane http://toblerity.github.com/shapely/"
