package:
  name: pygtk
  version: "2.24.0"

source:
  fn: pygtk-2.24.0.tar.bz2
  url: http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2


requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - zlib
    - pygobject # [py3k]
    - pygobject # [py2k]

  run:
    - python
    - zlib
    - pygobject # [py3k]
    - pygobject # [py2k]

build:
  number: 1

about:
  home: https://wiki.gnome.org/action/show/Projects/PyGObject?action=show&redirect=PyGObject
  license: GPLv3
  summary: "PYGTK"
